language: node_js
node_js:
- '8.5'
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_b4dca35b724b_key -iv $encrypted_b4dca35b724b_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
before_script:
- npm install
script:
- npm run build:prod
after_success:
- ssh -o StrictHostKeyChecking=no root@grid.best "sh ~/ci/deploy.sh"
addons:
  ssh_known_hosts: grid.best
